version: "3.9"

volumes:
  db-data:

services:
  app:
    build: 
        context: ./app
        dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - my_mongo_db
    networks:
      - "custom_network"
    
  my_mongo_db:
    build: "./db"
    ports:
      - 27017:27017
    networks:
      - "custom_network"
  
  contacts:
    build:
        context: ./contacts2
        dockerfile: Dockerfile
    ports:
     - "5000:5000"
    networks:
     - "custom_network"
     
networks:
  custom_network:
    driver: bridge
   